#stage-1
FROM node:14 as build

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build


#stage-2
# Stage 2
FROM nginx:1.17.0-alpine

COPY --from=build /app/build /usr/share/nginx/html