version: "3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  node-api:
    depends_on:
      - mysqldb
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  react-app:
    depends_on:
      - node-api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend
    volumes: 
      - ./client/src:/client/src
    environment:
      - WATCHPACK_POLLING=true

volumes:
  db:


networks:
  backend:
  frontend:

    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    # ports: 
    #   - "3000:3000"
    # volumes:
    #   - ./src:/app/src

    # env-file:
    #  - ./.env
